apiVersion: v1
kind: Service
metadata:
  name: my-prometheus
  namespace: monitoring
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9090
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: my-prometheus
    app.kubernetes.io/name: prometheus
