apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: vs-jenkins
  namespace: release
spec:
  hosts:
  - "jenkins.devops.id"
  gateways:
  - istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: jenkins.release.svc.cluster.local
